version: "3.8"
services:
    # PHP service
    app:
        build: .
        container_name: php-it-center
        working_dir: /var/www/app
        volumes:
            - ./:/var/www/app
        networks:
            - app-network
        links:
            - db
    db:
        image: postgres:12
        container_name: postgres-db
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-itcenter}
            POSTGRES_USER: ${POSTGRES_USER:-itcenter}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/app
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
